# Generated by Django 4.2.30 on 2026-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='martyr',
            new_name='martyrs_mar_last_na_317044_idx',
            old_name='martyrs_ma_last_na_d4f6e2_idx',
        ),
        migrations.RenameIndex(
            model_name='martyr',
            new_name='martyrs_mar_birth_p_c9161f_idx',
            old_name='martyrs_ma_birth_p_6b2b37_idx',
        ),
        migrations.RenameIndex(
            model_name='martyr',
            new_name='martyrs_mar_martyrd_6b2abd_idx',
            old_name='martyrs_ma_martyr_d_b5d659_idx',
        ),
        migrations.RenameIndex(
            model_name='martyr',
            new_name='martyrs_mar_militar_e68cdb_idx',
            old_name='martyrs_ma_militar_e0dbf4_idx',
        ),
        migrations.RenameIndex(
            model_name='memory',
            new_name='martyrs_mem_categor_593a4c_idx',
            old_name='martyrs_me_categor_11d3fb_idx',
        ),
        migrations.AddField(
            model_name='martyr',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='انتشار در سایت'),
        ),
    ]
