# Generated by Django 4.2.30 on 2026-08-24 15:30

import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('martyrs', '0002_rename_martyrs_ma_last_na_d4f6e2_idx_martyrs_mar_last_na_317044_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
            ],
            options={
                'verbose_name': 'رکورد تاریخچه',
                'verbose_name_plural': 'تاریخچه تغییرات',
                'ordering': ['-action_time'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.CreateModel(
            name='MartyrSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان بخش')),
                ('content', models.TextField(verbose_name='متن بخش')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('martyr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='martyrs.martyr', verbose_name='شهید')),
            ],
            options={
                'verbose_name': 'بخش سفارشی',
                'verbose_name_plural': 'بخش\u200cهای سفارشی',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
