# Generated by Django 4.2.30 on 2026-08-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0003_changelog_martyrsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComradeMartyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='نام و نام خانوادگی همرزم')),
                ('service_place', models.CharField(blank=True, max_length=220, verbose_name='محل خدمت با شهید')),
                ('memories', models.TextField(blank=True, verbose_name='خاطرات همرزم')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'همرزم شهید',
                'verbose_name_plural': 'همرزمان شهید',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MartyrInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_date', models.DateField(blank=True, null=True, verbose_name='تاریخ مجروحیت')),
                ('description', models.TextField(verbose_name='توضیحات مجروحیت')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مجروحیت',
                'verbose_name_plural': 'سوابق مجروحیت',
                'ordering': ['sort_order', 'injury_date', 'created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='martyr',
            name='martyrs_mar_militar_e68cdb_idx',
        ),
        migrations.RenameField(
            model_name='martyr',
            old_name='birth_place',
            new_name='birth_county',
        ),
        migrations.AlterField(
            model_name='martyr',
            name='birth_county',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهرستان تولد'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='birth_date_hijri',
            field=models.CharField(blank=True, help_text='مانند: ۱۵ شعبان ۱۳۶۲ قمری', max_length=80, verbose_name='تاریخ تولد (قمری)'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='birth_village',
            field=models.CharField(blank=True, max_length=100, verbose_name='روستای تولد'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='brigade',
            field=models.CharField(blank=True, max_length=180, verbose_name='تیپ'),
        ),
        migrations.RenameField(
            model_name='martyr',
            old_name='burial_place',
            new_name='burial_cemetery',
        ),
        migrations.AlterField(
            model_name='martyr',
            name='burial_cemetery',
            field=models.CharField(blank=True, max_length=160, verbose_name='نام محل دفن (قبرستان)'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='burial_county',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهرستان محل دفن'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='burial_plot',
            field=models.CharField(blank=True, max_length=100, verbose_name='قطعه'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='burial_village',
            field=models.CharField(blank=True, max_length=100, verbose_name='روستا یا شهر محل دفن'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='company',
            field=models.CharField(blank=True, max_length=180, verbose_name='گروهان'),
        ),
        migrations.RenameField(
            model_name='martyr',
            old_name='military_unit',
            new_name='division',
        ),
        migrations.AlterField(
            model_name='martyr',
            name='division',
            field=models.CharField(blank=True, max_length=180, verbose_name='لشکر'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='last_name_old',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی قدیم'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='platoon',
            field=models.CharField(blank=True, max_length=180, verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='martyr',
            name='unit_role',
            field=models.CharField(blank=True, max_length=180, verbose_name='مسئولیت در یگان'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد (شمسی)'),
        ),
        migrations.AlterField(
            model_name='martyr',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی (فعلی)'),
        ),
        migrations.AddIndex(
            model_name='martyr',
            index=models.Index(fields=['division'], name='martyrs_mar_divisio_409069_idx'),
        ),
        migrations.AddField(
            model_name='martyrinjury',
            name='martyr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='martyrs.martyr', verbose_name='شهید'),
        ),
        migrations.AddField(
            model_name='comrademartyr',
            name='martyr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comrades', to='martyrs.martyr', verbose_name='شهید'),
        ),
    ]
