# Generated by Django 4.2.30 on 2026-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0004_comrademartyr_martyrinjury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='martyr',
            name='battalion',
            field=models.CharField(blank=True, max_length=180, verbose_name='گردان'),
        ),
    ]
