# Generated by Django 4.2.30 on 2026-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0005_martyr_battalion'),
    ]

    operations = [
        migrations.AddField(
            model_name='martyr',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='martyrs/profiles/%Y/%m/', verbose_name='تصویر پروفایل'),
        ),
    ]
