# Generated by Django 4.2.30 on 2026-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0006_martyr_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_url', models.URLField(blank=True, default='http://dl.madahionline.ir/03-vafat-shahadat/Golchin-Madahi-Modafean-Haram/01-Golchin-Madahi-Modafean-Haram-(madahionline.ir).mp3', verbose_name='آدرس موزیک پس\u200cزمینه')),
                ('music_enabled', models.BooleanField(default=False, verbose_name='فعال\u200cسازی موزیک پس\u200cزمینه')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
