# Generated by Django 4.2.30 on 2026-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martyrs', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='music_file',
            field=models.FileField(blank=True, upload_to='music/', verbose_name='فایل موزیک'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='music_url',
            field=models.URLField(blank=True, default='', verbose_name='آدرس موزیک پس\u200cزمینه'),
        ),
    ]
